language: java
jdk:
  - openjdk11
branches:
  only:
    - main
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
before_install:
  - chmod +x gradlew
install:
  - echo "> build mentoree-backend"
  -  "./gradlew clean build -Pjasypt.encryptor.password=$JASYPT_KEY"

before_deploy:
  - zip -r mentoree-webservice *
  - mkdir -p deploy
  - mv mentoree-webservice.zip deploy/mentoree-webservice.zip

deploy:
  - provider: s3
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"
    bucket: mentoree-rest-api
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: mentoree-rest-api
    key: mentoree.zip
    application: mentoree-webservice-codedeploy
    bundle_type: zip
    deployment_group: mentoree-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true

notifications:
  email:
    recipients:
      - wer0801@gmail.com