version: "3"

networks:
  mentoree-network:
    driver: bridge
    external: true

volumes:
  mentoree-persistence:
    external: true

services:
  mentoree-redis-master:
    image: bitnami/redis:6.2.10
    platform: linux/amd64
    hostname: mentoree-redis-master
    container_name: mentoree-redis-master
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=/run/secrets/redis-secret
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - mentoree-persistence:/app/redis
    networks:
      - mentoree-network

  mentoree-redis-slave-1:
    image: bitnami/redis:6.2.10
    platform: linux/amd64
    hostname: mentoree-redis-slave-1
    container_name: mentoree-redis-slave-1
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=mentoree-redis-master
      - REDIS_PASSWORD=/run/secrets/redis-secret
    ports:
      - "7000:7000"
    restart: always
    volumes:
      - mentoree-persistence:/app/redis
    networks:
      - mentoree-network

  mentoree-redis-slave-2:
    image: bitnami/redis:6.2.10
    platform: linux/amd64
    hostname: entoree-redis-slave-2
    container_name: mentoree-redis-slave-2
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=mentoree-redis-master
      - REDIS_PASSWORD=/run/secrets/redis-secret
    ports:
      - "7001:7001"
    restart: always
    volumes:
      - mentoree-persistence:/app/redis
    networks:
      - mentoree-network

  mentoree-backend:
    image: wer080/mentoree-backend:1.0
    container_name: mentoree-backend
    networks:
      - mentoree-network
    ports:
      - "8081:8081"
    volumes:
      - mentoree-persistence:/app/backend/
    environment:
      - PROFILE=real
      - ENCKEY=testkey
    depends_on:
      - mentoree-redis-master

  mentoree-front:
    image: wer080/mentoree-frontend:1.0
    container_name: mentoree-front
    networks:
      - mentoree-network
    ports:
      - "80:80"