version: "3"

networks:
  mentoree-network:
    driver: bridge
    external: true

volumes:
  mentoree-persistence:
    external: true

services:
  mentoree-redis:
    image: redis
    platform: linux/amd64
    container_name: mentoree-redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - mentoree-persistence:/app/redis
    networks:
      - mentoree-network

  mentoree-front:
    image: wer080/mentoree-frontend:1.0
    container_name: mentoree-front
    platform: linux/amd64
    ports:
      - "80:80"
      - "443:443"
    restart: always
    environment:
      - TZ=Asia/Seoul
    networks:
      - mentoree-network

  mentoree-backend:
    image: wer080/mentoree-backend:1.0
    container_name: mentoree-backend
    networks:
      - mentoree-network
    ports:
      - "8081:8081"
    volumes:
      - mentoree-persistence:/app/backend/
    environment:
      - PROFILE=real
      - ENCKEY=testkey
    depends_on:
      - mentoree-redis
