server:
  port: 8081

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false

  redis:
    host: mentoree-redis
    port: 6379

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mentoree-rds.cs3dyljun5gz.ap-northeast-2.rds.amazonaws.com:3306/mentoreedb
    username: mentoreeAdmin
    password: ENC(UWv3hEx4cT2Mb6+PeoN0d8r9ZJzdH+wF) # 암호화 필요

  sql:
    init:
      mode: always

  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    open-in-view: false
    show-sql: true
    defer-datasource-initialization: true

  jwt:
    secret-key: ENC(VG+d6aUDx5uSAw/Cz1vv9OQJgGWoNRwO/pr+upHcIGRdE5FmOegkh2KGqEDk6Wy8)
    accessToken:
      validation: 600000 # 60 초
    refreshToken:
      validation: 1296000000 # 14일

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: client-id #google client id
            client-secret: client-secret  #암호화 필요
            scope:
              - profile
              - email

encrypt:
  key: ENC(rMJON7kU7wrq0ECPrihtsB7LMogy/v4KMzNjf0Bc+srj2YY5M5BCqfg1va8nYY2w)

cloud:
  aws:
    credentials:
      access-key: ENC(Ul6Pktj0JrJ4wMMxJYKDZE6GRgx0qlFUNNtJaLVQ8oQ=)
      secret-key: ENC(FgTc05yVN38ZEwIE+hABh9dzwpT4tP++Smm6QHxWS0MQLWo6CICY+msJJYWBiEpFJKGHBTtHGzA=)
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: cicd-mentoree-s3
